### ISSUE TITLE
Bug en FlatMap

### ISSUE THREAD

**Issue by avg0043** [ger86/recetas-javascripteras#5]
Hola Gerardo, 

Lo primero, enhorabuena por este tremendo curro de recetas de JS ! 🏅
Estaba haciendo un repaso de tus recetas, y creo que tienes un mini bug dentro de la sección "1. Object & Arrays / 08.FlatMap.md", en concreto en el ejemplo en el que estás usando `.flapMap()`:

```
const doneTasks = tasks.flatMap(task => [task, '✅']).flat(); 
```
Si no estoy equivocado, la llamada final a la función `.flat()` no es necesaria en este caso

Un saludo!

**Comment by ger86** [comment]
Hola! 

tienes toda la razón. Ya he hecho un commit corrigiendo esto. Muchas gracias por avisar :)
